/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestSetupRouteImport } from './routes/test.setup'
import { Route as TestRunRouteImport } from './routes/test.run'
import { Route as TestResultsRouteImport } from './routes/test.results'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSetupRoute = TestSetupRouteImport.update({
  id: '/test/setup',
  path: '/test/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRunRoute = TestRunRouteImport.update({
  id: '/test/run',
  path: '/test/run',
  getParentRoute: () => rootRouteImport,
} as any)
const TestResultsRoute = TestResultsRouteImport.update({
  id: '/test/results',
  path: '/test/results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/test/results': typeof TestResultsRoute
  '/test/run': typeof TestRunRoute
  '/test/setup': typeof TestSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/test/results': typeof TestResultsRoute
  '/test/run': typeof TestRunRoute
  '/test/setup': typeof TestSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/test/results': typeof TestResultsRoute
  '/test/run': typeof TestRunRoute
  '/test/setup': typeof TestSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/test/results'
    | '/test/run'
    | '/test/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/test/results'
    | '/test/run'
    | '/test/setup'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/test/results'
    | '/test/run'
    | '/test/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  TestResultsRoute: typeof TestResultsRoute
  TestRunRoute: typeof TestRunRoute
  TestSetupRoute: typeof TestSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/setup': {
      id: '/test/setup'
      path: '/test/setup'
      fullPath: '/test/setup'
      preLoaderRoute: typeof TestSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/run': {
      id: '/test/run'
      path: '/test/run'
      fullPath: '/test/run'
      preLoaderRoute: typeof TestRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/results': {
      id: '/test/results'
      path: '/test/results'
      fullPath: '/test/results'
      preLoaderRoute: typeof TestResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  TestResultsRoute: TestResultsRoute,
  TestRunRoute: TestRunRoute,
  TestSetupRoute: TestSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
